# Generated by Django 3.2.2 on 2021-05-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='st_admin_data',
            name='Fine',
            field=models.IntegerField(default=0),
        ),
    ]
